VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/sorting_network_pkg.vhd\
	src/sorting_network.vhd\
	tb/sorting_network_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=sorting_network_tb
WAVE_FILE=wave.do

include ../../util/simple_flow.mk

include ../../util/quartus.mk