VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/running_light.vhd\
	tb/running_light_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=running_light_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw

include ../../util/simple_flow.mk

include ../../util/quartus.mk

