VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/lfsr.vhd\
	tb/lfsr_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=lfsr_tb
WAVE_FILE=wave.do

include ../../util/simple_flow.mk

include ../../util/quartus.mk
