VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	../../lib/top/src/top.vhd\
	src/bin2dec_pkg.vhd\
	src/bin2dec.vhd\
	src/stopwatch.vhd\
	src/timer.vhd\
	top_arch.vhd\
	tb/watch_tb.vhd

TB=watch_tb
WAVE_FILE=wave.do

include ../../util/simple_flow.mk

include ../../util/quartus.mk
