VHDL_FILES =\
	src/adder4_pkg.vhd \
	src/or_gate.vhd \
	src/xor_gate.vhd \
	src/and_gate.vhd \
	src/halfadder.vhd \
	src/fulladder.vhd \
	src/adder4.vhd \
	tb/adder4_tb.vhd


TB=adder4_tb
WAVE_FILE=wave.do

include ../../util/simple_flow.mk
