VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/pwm_signal_generator.vhd\
	tb/pwm_signal_generator_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=pwm_signal_generator_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtk

include ../../util/simple_flow.mk

include ../../util/quartus.mk

