VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/sram_ctrl_pkg.vhd\
	src/test_sequence_pkg.vhd\
	src/sequence_fsm.vhd\
	src/sram_ctrl.vhd\
	tb/sram_pkg.vhd\
	tb/sram.vhd\
	tb/sram_ctrl_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=sram_ctrl_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtkw

include ../../util/simple_flow.mk

include ../../util/quartus.mk

