VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	src/sram_pkg.vhd \
	src/sram.vhd \
	tb/sram_tb.vhd\
	tb/sram_tb_sample_solution.vhd


TB=sram_tb_sample_solution
WAVE_FILE=wave.do

include ../../util/simple_flow.mk
