VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd \
	../../lib/vhdldraw/src/vhdldraw_pkg.vhd \
	src/checkerboard.vhd\
	src/ouchi.vhd\
	src/concentric.vhd\
	src/squarecircle.vhd\
	src/illusions.vhd


TB=illusions
WAVE_FILE=wave.do

include ../../util/simple_flow.mk
