CLEAN_FILES=*.ppm

VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/vhdldraw/src/vhdldraw_pkg.vhd\
	src/barcode_pkg.vhd \
	src/barcode.vhd


TB=barcode
WAVE_FILE=wave.do

include ../../util/simple_flow.mk
