VHDL_FILES =\
	../../lib/math/src/math_pkg.vhd\
	../../lib/util/src/util_pkg.vhd\
	src/bcd_fsm.vhd\
	tb/bcd_fsm_tb.vhd\
	../../lib/top/src/top.vhd\
	top_arch.vhd

TB=bcd_fsm_tb
WAVE_FILE=wave.do
GTK_WAVE_FILE=wave.gtk

include ../../util/simple_flow.mk

include ../../util/quartus.mk

